### PR TITLE
Add (basic) type information

### PR DESCRIPTION
**Pull request by calpaterson**
Hi!  This PR adds very basic type information to this library.  This adds one new runtime dependency (typing, to continue support for 2.x) and one new development dependency: mypy.

My motive for doing this is to get type information added to furl which would help me in a private project.

### CODE REVIEW

**Comment by calpaterson** [comment]
Hmm.  Looks like the build failed for 2.6 because travis's current ubuntu release doesn't provide 2.6.  Looks like they removed support for the last one that did (trusty) too.  What should I do?

**Comment by calpaterson** [comment]
Hurrah

**Comment by gruns** [comment]
Awesome!

> My motive for doing this is to get type information added to furl which would help me in a private project.

Double awesome.

I don't have much experience with typing. Is it possible at all to avoid the `typing` dependency in Python 2.x?

**Comment by calpaterson** [comment]
Ok, I've done that - this means that you won't be able to typecheck on less than python 3.5 but probably that is not a big deal

**Comment by calpaterson** [comment]
Hi - I removed the dependency as suggested.  Is there anything left I can do to get this merged?

**Comment by gruns** [comment]
Thanks Cal. Looks awesome!

So, in conclusion before being merged: this adds typing support to Python 3.5+ with no new runtime dependencies, now that `typing` was culled from Python 2.x, correct?

Also is

```
[mypy-setup]
ignore_errors = True
```

acceptable to adopt? Pardon my ignorance here; I haven't played with mypy yet.

**Comment by calpaterson** [comment]
Makes sense that you're double checking :)

Yes, this adds typing support to 3.5+ with no new runtime dependencies.

That `[mypy-setup]` snippet is [telling mypy](https://mypy.readthedocs.io/en/stable/config_file.html#per-module-and-global-options) to ignore type errors in your setup.py file (ie: your setuptools config).  In other projects I usually don't typecheck setup.py files. Last I checked setuptools doesn't provide type information anyway.

**Comment by gruns** [comment]
Awesome. Merged!

Thank you so much, Cal. Sincerely. Please let me know how I can help you similarly add typing to furl, too. Both libraries, and all software that uses them, will be better for it.

**Comment by calpaterson** [comment]
Ok!  I have a semi-working local branch of furl with typing working and will raise that as a PR when i get a minute :)

**Pull request merged**
